### ISSUE TITLE
cannot load such file -- zip/zip (LoadError)

### ISSUE THREAD

**Issue by hey-jude** [josegonzalez/ruby-redis-backup#3]
I installed it and executed, but failed with below messages.
It seems rubyzip version problem.
- http://stackoverflow.com/questions/12079291/rails-3-loaderror-cannot-load-such-file-zip-zip/19506372#19506372

```
/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- zip/zip (LoadError)
    from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /usr/local/rvm/gems/ruby-2.1.5/gems/redis-backup-0.0.3/bin/redis-backup:11:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-2.1.5/bin/redis-backup:23:in `load'
    from /usr/local/rvm/gems/ruby-2.1.5/bin/redis-backup:23:in `<main>'
    from /usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
    from /usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

$ gem list

**\* LOCAL GEMS ***

aws-sdk (1.59.0)
aws-sdk-v1 (1.59.0)
bigdecimal (1.2.4)
bundler (1.7.6)
bundler-unload (1.0.2)
executable-hooks (1.3.2)
gem-wrappers (1.2.7)
io-console (0.4.2)
json (1.8.1)
mini_portile (0.6.1)
minitest (4.7.5)
nokogiri (1.6.4.1)
psych (2.0.5)
rake (10.1.0)
rdoc (4.1.0)
redis (3.1.0)
redis-backup (0.0.3)
rubygems-bundler (1.4.4)
rubyzip (1.1.6)
rvm (1.11.3.9)
test-unit (2.1.5.0)

**Comment by josegonzalez** [comment]
Can you try a6e50061de39e94ea1a0b17617dca407758b08c4 and see if that works? If so, I'll make a new release.

**Comment by hey-jude** [comment]
It's worked, thanks!

**Comment by sdbondi** [comment]
This version has not been pushed to rubygems. Please make a release - thanks

**Comment by josegonzalez** [comment]
The release was pushed, sorry about that.

**Comment by sdbondi** [comment]
No problem - thanks @josegonzalez :+1:
